services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: recyclic
      POSTGRES_USER: recyclic
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U recyclic"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - recyclic-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - recyclic-network

  api:
    build: ./api
    image: recyclic-api:${API_IMAGE_TAG:-latest}
    environment:
      DATABASE_URL: postgresql://recyclic:${POSTGRES_PASSWORD}@postgres:5432/recyclic
      REDIS_URL: redis://redis:6379
      SECRET_KEY: ${SECRET_KEY}
      ENVIRONMENT: development
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - recyclic-network

  bot:
    build: ./bot
    image: recyclic-bot:${BOT_IMAGE_TAG:-latest}
    environment:
      DATABASE_URL: postgresql://recyclic:${POSTGRES_PASSWORD}@postgres:5432/recyclic
      REDIS_URL: redis://redis:6379
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      API_BASE_URL: http://api:8000
      FRONTEND_URL: ${FRONTEND_URL}
      ADMIN_TELEGRAM_IDS: ${ADMIN_TELEGRAM_IDS}
      ENABLE_INLINE_BUTTONS: ${ENABLE_INLINE_BUTTONS}
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      api:
        condition: service_healthy
    networks:
      - recyclic-network

  frontend:
    build:
      context: ./frontend
      args:
        REACT_APP_API_URL: http://api:8000
    image: recyclic-frontend:${FRONTEND_IMAGE_TAG:-latest}
    ports:
      - "4444:80"
    depends_on:
      - api
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:5173/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - recyclic-network

volumes:
  postgres_data:

networks:
  recyclic-network:
    driver: bridge