"""Add Story 4.2 classification fields

Revision ID: 42a7f3e9c5d1
Revises: 3f67c2e8edc1
Create Date: 2025-09-15 22:45:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '42a7f3e9c5d1'
down_revision = '3f67c2e8edc1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Update DepositStatus enum to include new statuses
    op.execute("ALTER TYPE depositstatus ADD VALUE 'PENDING_VALIDATION'")
    op.execute("ALTER TYPE depositstatus ADD VALUE 'CLASSIFICATION_FAILED'")

    # Add new columns for Story 4.2 classification features
    op.add_column('deposits', sa.Column('transcription', sa.Text(), nullable=True))
    op.add_column('deposits', sa.Column('eee_category', sa.Enum('SMALL_APPLIANCE', 'LARGE_APPLIANCE', 'IT_EQUIPMENT', 'LIGHTING', 'TOOLS', 'TOYS', 'MEDICAL_DEVICES', 'MONITORING_CONTROL', 'AUTOMATIC_DISPENSERS', 'OTHER', name='eeecategory'), nullable=True))
    op.add_column('deposits', sa.Column('confidence_score', sa.Float(), nullable=True))
    op.add_column('deposits', sa.Column('alternative_categories', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Remove the new columns
    op.drop_column('deposits', 'alternative_categories')
    op.drop_column('deposits', 'confidence_score')
    op.drop_column('deposits', 'eee_category')
    op.drop_column('deposits', 'transcription')

    # Note: PostgreSQL doesn't support removing enum values easily
    # In a production environment, you would need to recreate the enum
    # For now, we leave the enum values in place

    # ### end Alembic commands ###